Revert "clear out some bashisms from wrapper scripts"
This reverts commit 3d45d8ee14bebcc572903ae3cb48bf57f21e612b.

This broke various builds because the commands being used don't
replace the ones being removed.
which llvm-ar -- checks if llvm-ar is in the PATH
command llvm-ar -- runs llvm-ar and returns its return value (failing
unconditionally because calling llvm-ar without arguments fails)

There's also no need to avoid echo (internal command in any shell)
in favor of printf (external command, extra time spent spawning) unless
special features of printf are needed.

diff --git a/nm b/nm
--- a/nm
+++ b/nm
@@ -9,12 +9,12 @@ if [ -z "$PARENT" ]; then
 	WRAPPED=true
 # If we're being called by gcc-nm or llvm-nm, we're already
 # wrapped (and need to make sure we don't call ourselves recursively)
-elif printf "%s\n" "$PARENT" |grep -qE -- '-nm$'; then
+elif echo "$PARENT" |grep -qE -- '-nm$'; then
 	WRAPPED=true
 # Fun... We're running inside qemu binfmt_misc emulation,
 # so we have to determine our parent the evil and less
 # reliable way...
-elif printf "%s\n" "$PARENT" |grep -qE -- 'qemu'; then
+elif echo "$PARENT" |grep -qE -- 'qemu'; then
 	if grep -qE -- '-nm' /proc/$PPID/cmdline; then
 		WRAPPED=true
     fi
@@ -24,18 +24,18 @@ fi
 # already wrapped...
 if ! "$WRAPPED"; then
 
-	command llvm-nm &>/dev/null && IS_LLVM_NM=true
-	command gcc-nm &>/dev/null && IS_GCC_NM=true
-	[ -z "$IS_GCC_NM" ] && printf "%s\n" "${0}-wrapper ERROR: GCC-NM missing, cannot continue!" && exit 1
+	which llvm-nm &>/dev/null && IS_LLVM_NM=true
+	which gcc-nm &>/dev/null && IS_GCC_NM=true
+	[[ -z "$IS_GCC_NM" ]] && echo "${0}-wrapper ERROR: GCC-NM missing, cannot continue!" && exit 1
     for i in "$@"; do
-		[ "$(printf "%s\n" $i |cut -b1)" = '-' ] && continue
-		if printf "%s\n" "$i" |grep -qE '\.(o|a)$' && [ -e "$i" ]; then
+		[ "$(echo $i |cut -b1)" = '-' ] && continue
+		if echo "$i" |grep -qE '\.(o|a)$' && [ -e "$i" ]; then
 			if LANG=C gcc-nm "$i" 2>&1 |grep -qi "file format not recognized"; then
-				if [ -n "$IS_LLVM_NM" ]; then
+				if [[ -n "$IS_LLVM_NM" ]]; then
 					REAL_NM=llvm-nm
 					break
 				else
-					printf "%s\n" "${0}-wrapper ERROR: LLVM-LTO code but missing llvm-nm, cannot continue!"
+					echo "${0}-wrapper ERROR: LLVM-LTO code but missing llvm-nm, cannot continue!"
 					exit 1
 				fi
 			fi
diff --git a/ranlib b/ranlib
--- a/ranlib
+++ b/ranlib
@@ -10,12 +10,12 @@ if [ -z "$PARENT" ]; then
 # If we're being called by gcc-ranlib or llvm-ranlib,
 # we're already wrapped (and need to make sure we don't
 # call ourselves recursively)
-elif printf "%s\n" "$PARENT" |grep -qE -- '-ranlib$'; then
+elif echo "$PARENT" |grep -qE -- '-ranlib$'; then
 	WRAPPED=true
 # Fun... We're running inside qemu binfmt_misc emulation,
 # so we have to determine our parent the evil and less
 # reliable way...
-elif printf "%s\n" "$PARENT" |grep -qE -- 'qemu'; then
+elif echo "$PARENT" |grep -qE -- 'qemu'; then
 	if grep -qE -- '-ranlib' /proc/$PPID/cmdline; then
 		WRAPPED=true
 	fi
@@ -23,29 +23,29 @@ fi
 # If we're being called by gcc-ranlib or llvm-ranlib, we're
 # already wrapped
 if ! "$WRAPPED"; then
-	command llvm-ranlib &>/dev/null && HAVE_LLVM_RANLIB=true
-	command gcc-ranlib &>/dev/null && HAVE_GCC_RANLIB=true
-	command gcc-nm &>/dev/null && HAVE_GCC_NM=true
-	[ -z "$HAVE_GCC_NM" ] && printf "%s\n" "${0}-wrapper ERROR: GCC-NM missing, cannot continue!" && exit 1
+	which llvm-ranlib &>/dev/null && HAVE_LLVM_RANLIB=true
+	which gcc-ranlib &>/dev/null && HAVE_GCC_RANLIB=true
+	which gcc-nm &>/dev/null && HAVE_GCC_NM=true
+	[[ -z "$HAVE_GCC_NM" ]] && echo "${0}-wrapper ERROR: GCC-NM missing, cannot continue!" && exit 1
 
 	for i in "$@"; do
-		[ "$(printf "%s\n" $i |cut -b1)" = '-' ] && continue
-		if printf "%s\n" "$i" |grep -qE '\.(o|a)$' && [ -e "$i" ]; then
+		[ "$(echo $i |cut -b1)" = '-' ] && continue
+		if echo "$i" |grep -qE '\.(o|a)$' && [ -e "$i" ]; then
 			if LANG=C gcc-nm "$i" 2>&1 |grep -qi "file format not recognized"; then
-				if [ -n "$HAVE_LLVM_RANLIB" ]; then
+				if [[ -n "$HAVE_LLVM_RANLIB" ]]; then
 					REAL_RANLIB=llvm-ranlib
 					break
 				else
-					printf "%s\n" "${0}-wrapper ERROR: LLVM-LTO code but missing llvm-ranlib, cannot continue!"
+					echo "${0}-wrapper ERROR: LLVM-LTO code but missing llvm-ranlib, cannot continue!"
 					exit 1
 				fi
 			fi
 			if LANG=C readelf -s "$i" | grep -q "gnu_lto"; then
-				if [ -n "$HAVE_GCC_RANLIB" ]; then
+				if [[ -n "$HAVE_GCC_RANLIB" ]]; then
 					REAL_RANLIB=gcc-ranlib
 					break
 				else
-					printf "%s\n" "${0}-wrapper ERROR: GCC-LTO code but missing gcc-ranlib, cannot continue!"
+					echo "${0}-wrapper ERROR: GCC-LTO code but missing gcc-ranlib, cannot continue!"
 					exit
 				fi
 			fi
